version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  addition:
    build: ./subprojects/addition
    container_name: addition
    ports:
      - "8001:8000"
    depends_on:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
    # Addition popper sidecar
    extra_hosts:
      - "host.docker.internal:host-gateway"

  addition_popper:
    build: ./subprojects/proxy_popper
    container_name: addition_popper
    depends_on:
      - rabbitmq
      - addition
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - SERVICE_NAME=addition
      - DOWNSTREAM_URL=http://addition:8000/add
    # Optional: expose for debugging
    ports:
      - "9001:8000"

  addition2:
    build: ./subprojects/addition
    container_name: addition2
    ports:
      - "8004:8000"
    depends_on:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
    extra_hosts:
      - "host.docker.internal:host-gateway"

  addition2_popper:
    build: ./subprojects/proxy_popper
    container_name: addition2_popper
    depends_on:
      - rabbitmq
      - addition2
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - SERVICE_NAME=addition
      - DOWNSTREAM_URL=http://addition2:8000/add
    ports:
      - "9004:8000"

  subtraction:
    build: ./subprojects/subtraction
    container_name: subtraction
    ports:
      - "8002:8000"
    depends_on:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
    extra_hosts:
      - "host.docker.internal:host-gateway"

  subtraction_popper:
    build: ./subprojects/proxy_popper
    container_name: subtraction_popper
    depends_on:
      - rabbitmq
      - subtraction
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - SERVICE_NAME=subtraction
      - DOWNSTREAM_URL=http://subtraction:8000/subtract
    ports:
      - "9002:8000"

  file_splitter:
    build: ./subprojects/file_splitter
    container_name: file_splitter
    ports:
      - "8010:8000"
    environment:
      - PYTHONUNBUFFERED=1
    extra_hosts:
      - "host.docker.internal:host-gateway"

  file_hasher:
    build: ./subprojects/file_hasher
    container_name: file_hasher
    ports:
      - "8011:8000"
    environment:
      - PYTHONUNBUFFERED=1
    extra_hosts:
      - "host.docker.internal:host-gateway"

  api:
    build: ./subprojects/api
    container_name: api
    depends_on:
      - addition
      - subtraction
      - proxy_pusher
      - file_splitter
      - file_hasher
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - ADDITION_URL=http://proxy_pusher:8000/proxy/addition
      - SUBTRACTION_URL=http://proxy_pusher:8000/proxy/subtraction
      - FILE_SPLITTER_URL=http://file_splitter:8000/split
      - FILE_HASHER_URL=http://file_hasher:8000/hash
    extra_hosts:
      - "host.docker.internal:host-gateway"

  proxy_pusher:
    build: ./subprojects/proxy_pusher
    container_name: proxy_pusher
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    ports:
      - "9100:8000"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    depends_on:
      - api

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus 